### ISSUE TITLE
The character shall turn according to the direction

### ISSUE THREAD

**Issue by mmyumu** [mmyumu/TroncGame#12]
For now, the character is always looking at the south direction, he should be able to turn according to the direction he's moving to.

The options for that are:
- rotating the sprite to match the direction
- load a sprite per direction

**Comment by mmyumu** [comment]
Rotating the sprite needs just 1 sprite
But it would not work if the character is not drawn top-down

**Comment by Garulfo84** [comment]
maybe we could follow this tips
http://fabrique-jeu-video.blogspot.fr/2013/09/lanimation-du-personnage.html

and load an animation per direction

**Comment by mmyumu** [comment]
Yes, this question is obsolete since we updated the characters models (now we know the character will not be drawn "top-down")
So rotating the sprite does not work and we need multiple animations for each directions.
